absolutemomentum:
  ALLOW_SHORT: false
  LOOKBACK_DAYS: 36
  SHORT_LOOKBACK_DAYS: 111
  SHORT_THRESH: -0.3898208551647424
atrchanneltrend:
  ATR_MULT: 1.9503155625979154
  ATR_PERIOD: 11
  EMA_PERIOD: 37
basisreversion:
  ENTRY_Z: 2.072431464957444
  EXIT_Z: 1.1392371403247157
  LONG_ZSCORE_WINDOW: 1927
  ZSCORE_WINDOW: 397
bbbreakoutobv:
  BB_PERIOD: 34
  BB_STD: 2.5
  OBV_EMA: 24
commodityriskappetite: {}
donchianbreakout:
  DONCHIAN_PERIOD: 13
  EXIT_PERIOD: 7
dualmomentum:
  ALLOW_SHORT: false
  FAST_LOOKBACK: 29
  SHORT_LOOKBACK: 88
  SHORT_THRESH: -0.22095570093203648
  SLOW_LOOKBACK: 93
  VOL_LOWER: 0.2291571693582509
  VOL_UPPER: 0.9865986449239813
ematrendregime:
  BULL_THRESH: 0.12813089278546697
  BULL_WINDOW: 42
  DAILY_EMA: 71
  EMA_FAST: 8
  EMA_SLOW: 22
  RSI_LONG_MIN: 38
  RSI_PERIOD: 20
  RSI_SHORT_MAX: 58
fundingcarrymomentum: {}
fundingratereversion:
  ENTRY_Z: 2.2718141732449553
  EXIT_Z: 0.9650277259102091
  ZSCORE_WINDOW: 276
liquidationflow:
  LIQ_ENTRY_Z: 1.4168070125074628
  LIQ_ZSCORE_WINDOW: 33
  LONG_THRESHOLD: 0.7559127607648048
  LS_ENTRY_Z: 1.9486556866481375
  LS_ZSCORE_WINDOW: 31
  OI_CHANGE_WINDOW: 8
  PRICE_CHANGE_WINDOW: 7
macdsignalcross:
  HIST_MIN: 0.6421165119131431
  MACD_FAST: 13
  MACD_SIGNAL: 10
  MACD_SLOW: 33
macroregime:
  DXY_WEIGHT: 1.8762050216831603
  LONG_THRESHOLD: 1.4292864749964733
  RETURN_LOOKBACK: 10
  SHORT_THRESHOLD: -1.906604342433234
  SPX_WEIGHT: 0.7000086583355434
  VIX_HIGH: 22
  VIX_LOW: 14
  VIX_WEIGHT: 0.6820378987840766
maregime:
  ALLOW_SHORT: false
  SMA_DAYS: 120
momentumcomposite:
  BB_PERIOD: 12
  BB_STD: 2.5
  EXIT_THRESHOLD: 0.09406130588232278
  LONG_THRESHOLD: 0.8148654558789665
  RSI_PERIOD: 12
  SHORT_THRESHOLD: -0.5784421934510993
rsitrendmomentum:
  BEAR_RSI_MAX: 48
  BULL_RSI_MIN: 51
  EMA_TREND: 62
  RSI_PERIOD: 13
sentimentflow:
  FNG_EXTREME_FEAR: 16
  FNG_EXTREME_GREED: 72
  FNG_MOMENTUM_WINDOW: 14
  LONG_THRESHOLD: 1.9401493282083886
  SHORT_THRESHOLD: -1.7785553828780316
  STABLE_DECLINE_THRESHOLD: -0.006878422550516064
  STABLE_GROWTH_THRESHOLD: 0.015405128416166862
stochasticemacross:
  EMA_FAST: 14
  EMA_SLOW: 22
  STOCH_D: 7
  STOCH_K: 9
supertrendobv:
  OBV_EMA: 13
  ST_MULT: 3.3784742806494314
  ST_PERIOD: 10
  TBR_WINDOW: 38
volatilitycarry:
  IV_RV_EXIT: 1.0174941596424008
  IV_RV_LONG: 1.331145698281023
  SMA_DAYS: 41
volatilityregime:
  DVOL_MOMENTUM_HOURS: 18
  IV_RV_EXIT_HIGH: 1.0375146591845597
  IV_RV_EXIT_LOW: 0.7116053690744114
  IV_RV_HIGH: 1.5475987589205187
  IV_RV_LOW: 0.4125053776113335
  RV_COMPRESSION_PCTILE: 12
  RV_WINDOW_HOURS: 93
volsqueezebreakout:
  BB_PERIOD: 26
  BB_STD: 2.0
  WIDTH_PCTILE_THRESH: 0.3582339106703495
  WIDTH_PCTILE_WINDOW: 100
vwaprsireversion:
  OVERBOUGHT: 72
  OVERSOLD: 27
  RSI_PERIOD: 11
  VWAP_WINDOW_DAYS: 8
weekendeffect: {}
weeklytrend:
  MOMENTUM_WEEKS: 12
  SMA_WEEKS: 50
